namespace Kingmaker.Code.UI.MVVM.View.Overtips.MapObject.Console;

public class MapObjectOvertipsConsoleView : MapObjectOvertipsView<OvertipTransitionConsoleView, OvertipMapObjectSimpleConsoleView, OvertipMapObjectInteractionConsoleView, OvertipDestructibleObjectConsoleView, OvertipMapObjectTwitchDropsConsoleView>
{
}
