namespace Kingmaker.UnitLogic.Levelup.Selections;

public enum FeatureGroup
{
	None = 0,
	Attribute = 1,
	Skill = 2,
	Talent = 3,
	UltimateAbility = 4,
	ActiveAbility = 5,
	ChargenHomeworld = 6,
	ChargenOccupation = 7,
	ChargenDarkestHour = 8,
	ChargenMomentOfTriumph = 9,
	ChargenAttribute = 10,
	ChargenSkill = 11,
	ChargenCareerPath = 12,
	ChargenShip = 13,
	BackgroundFeature = 14,
	AdvancedAbility = 15,
	ShipUpgrade = 16,
	AscensionTalent = 17,
	FirstCareerTalent = 18,
	SecondCareerTalent = 19,
	FirstCareerAbility = 20,
	SecondCareerAbility = 21,
	CommonTalent = 22,
	FirstOrSecondCareerTalent = 23,
	FirstOrSecondCareerAbility = 24,
	ChargenSoulMark = 25,
	ChargenNavigator = 26,
	ChargenImperialWorld = 30,
	ChargenPsyker = 31,
	ChargenForgeWorld = 32,
	ShipActiveAbility = 33,
	ShipUltimateAbility = 34
}
