namespace Owlcat.Runtime.UI.ConsoleTools.NavigationTool;

public interface INavigationDirectionsHandler : INavigationVerticalDirectionsHandler, INavigationUpDirectionHandler, IConsoleEntity, INavigationDownDirectionHandler, INavigationHorizontalDirectionsHandler, INavigationLeftDirectionHandler, INavigationRightDirectionHandler
{
}
