namespace Kingmaker.UI.Common;

public enum ItemsFilterType
{
	NoFilter = 0,
	Weapon = 1,
	Armor = 2,
	Accessories = 3,
	Usable = 4,
	Notable = 5,
	NonUsable = 6,
	Scroll = 7,
	Wand = 8,
	Utility = 9,
	Potion = 10,
	Recipe = 11,
	Unlearned = 12,
	ShipNoFilter = 13,
	ShipWeapon = 14,
	ShipOther = 15,
	PlasmaDrives = 16,
	VoidShieldGenerator = 17,
	AugerArray = 18,
	ArmorPlating = 19,
	Dorsal = 20,
	Prow = 21,
	Port = 22,
	Starboard = 23,
	Arsenal = 24,
	AugmentationsAll = 25,
	AugmentationsArms = 26,
	AugmentationsEyes = 27,
	AugmentationsLegs = 28,
	AugmentationsSystems = 29,
	AugmentationsTorso = 30,
	AugmentationsMisc = 31,
	AugmentationsItems = 33,
	AugmentationsNoFilter = 34
}
